# https://docs.github.com/en/actions/guides/building-and-testing-python

name: CI
on:
  push:
    branches-ignore: [master]
    paths-ignore: ['docs/**']
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { python: 3.6, os: ubuntu-18.04, compiler: clang, arguments: -O0 }
        - { python: 3.7, os: ubuntu-20.04, compiler: clang, arguments: -O1 }
        - { python: 3.8, os: ubuntu-18.04, compiler: gcc, arguments: -O2 }
        - { python: 3.9, os: ubuntu-20.04, compiler: gcc, arguments: -O3 }
        - { python: 3.10-dev, os: ubuntu-20.04, compiler: clang, arguments: -O3 }
        - { python: pypy-3.6, os: ubuntu-18.04, compiler: gcc, arguments: -O0 }
        - { python: pypy-3.7, os: ubuntu-20.04, compiler: clang, arguments: -O2 }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip wheel setuptools
        pip install -r test/requirements.txt
        python --version
    - name: Install compiler
      run: |
        sudo apt update
        sudo apt install ${{ matrix.compiler }}
        ${{ matrix.compiler }} --version
    - name: Run tests
      run: |
        python test.py -c ${{ matrix.compiler }} ${{ matrix.arguments }}
